version: '2'
services:
    db:
        image: mysql
        ports:
            - "3306:3306"
        expose:
            - "3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: symfony
            MYSQL_USER: symfony
            MYSQL_PASSWORD: symfony
    php:
        build: ./php-fpm
        ports:
            - "9001:9001"
        volumes:
            - ./symfony3:/var/www/symfony3:cached
            - ./logs/symfony:/var/www/symfony3/var/logs:cached
        links:
            - db
    nginx:
        build: ./nginx
        ports:
            - "80:80"
        links:
            - php
        volumes_from:
            - php
        volumes:
            - ./logs/nginx/:/var/log/nginx:cached
