<?php

namespace AppBundle\Repository;

/**
 * GnomeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GnomeRepository extends \Doctrine\ORM\EntityRepository
{
}
